---
title: "Untitled"
author: Bihui Sun
output: github_document
---

# Problem 1
```{r}
library(tidyverse)

filename=list.files("C:/Users/lenovo/Desktop/p8105/data_import_examples",pattern="^con|^exp")
allname=tibble(filename)
allname

readdata=function(path){
  read_csv(file=path)
}

allpath=c("C:/Users/lenovo/Desktop/p8105/data_import_examples/con_01.csv","C:/Users/lenovo/Desktop/p8105/data_import_examples/con_02.csv","C:/Users/lenovo/Desktop/p8105/data_import_examples/con_03.csv","C:/Users/lenovo/Desktop/p8105/data_import_examples/con_04.csv","C:/Users/lenovo/Desktop/p8105/data_import_examples/con_05.csv","C:/Users/lenovo/Desktop/p8105/data_import_examples/con_06.csv","C:/Users/lenovo/Desktop/p8105/data_import_examples/con_07.csv","C:/Users/lenovo/Desktop/p8105/data_import_examples/con_08.csv","C:/Users/lenovo/Desktop/p8105/data_import_examples/con_09.csv","C:/Users/lenovo/Desktop/p8105/data_import_examples/con_10.csv","C:/Users/lenovo/Desktop/p8105/data_import_examples/exp_01.csv","C:/Users/lenovo/Desktop/p8105/data_import_examples/exp_02.csv","C:/Users/lenovo/Desktop/p8105/data_import_examples/exp_03.csv","C:/Users/lenovo/Desktop/p8105/data_import_examples/exp_04.csv","C:/Users/lenovo/Desktop/p8105/data_import_examples/exp_05.csv","C:/Users/lenovo/Desktop/p8105/data_import_examples/exp_06.csv","C:/Users/lenovo/Desktop/p8105/data_import_examples/exp_07.csv","C:/Users/lenovo/Desktop/p8105/data_import_examples/exp_08.csv","C:/Users/lenovo/Desktop/p8105/data_import_examples/exp_09.csv","C:/Users/lenovo/Desktop/p8105/data_import_examples/exp_10.csv")
alldata=map(allpath,readdata)

newdata=allname%>%
  mutate(alldata)%>%
  unnest(alldata)%>%
  separate(filename,into=c("subject","csv"),sep=6)%>%
  select(-csv)
 
newdata
newdata=newdata%>%
  gather(key=week,value=observation,week_1:week_8)
newdata
ggplot(newdata,aes(x = week, y = observation, color = subject)) + 
  geom_point()+
  geom_smooth(se = FALSE) +
  viridis::scale_color_viridis(
    name = "day", 
    discrete = TRUE
  )

```

* From the plot, we can find the observations in exp group is obviously higher than observations in control group.


# Problem 2
```{r}
library(tidyverse)

data=read_csv(file="C:/Users/lenovo/Desktop/p8105/data_import_examples/homicide-data.csv")
data
data=data%>%
  unite("city_state",c("city","state"))
data
totalhomicide=data%>%
  group_by(city_state)%>%
  summarize(total_homicide=n())%>%
  filter(!city_state=="Tulsa_AL")              #Remove the Tulsa_AL #
totalhomicide
unsolved=data%>%
  group_by(city_state)%>%
  filter(disposition%in%c("Closed without arrest","Open/No arrest"))%>%
  summarize(unsolved_homicide=n())
unsolved  

baltimore_total=filter(totalhomicide,city_state=="Baltimore_MD")
baltimore_total
baltimore_unsolved=filter(unsolved,city_state=="Baltimore_MD")
baltimore_unsolved
result=prop.test(baltimore_unsolved$unsolved_homicide,baltimore_total$total_homicide)
result
result_tidy=broom::tidy(result)
result_tidy
result_tidy%>%pull(estimate)
result_tidy%>%pull(conf.low)
result_tidy%>%pull(conf.high)

total_result=map2(unsolved$unsolved_homicide,totalhomicide$total_homicide,prop.test)%>%
  map(broom::tidy)
total_data=left_join(unsolved,totalhomicide)
all_proportion=mutate(total_data,total_result)%>%
  unnest(total_result)%>%
  select(city_state,unsolved_homicide,total_homicide,estimate,conf.low,conf.high)
all_proportion
all_proportion%>%
  mutate(city_state = forcats::fct_reorder(city_state, estimate))%>%
  ggplot(aes(x=city_state,y=estimate))+
  geom_point()+
  geom_errorbar(aes(ymin=conf.low,ymax=conf.high))+
  theme(axis.text.x = element_text(angle = 90, hjust = 1))

  
  


```

* This data collects data of homicide criminals from 50 states in US,including 52179 observations and 12 variables, variables include their name,sex,age,race,living city,report date and disposition status. 